#!/usr/bin/env ruby

#pipe in a fasta.  writes to stdout.

first = true
while(true)
	line = $stdin.gets
	break if line == nil
	if line.include?('>')
		if not first
			puts
		end
		first = false
		
		puts line
	else
		print line.chomp
	end
end
